### PR TITLE
Upgrade to 2.6.0 using FormAction

### PR DESCRIPTION
**Pull request by wsargent**
Reworked form example using playframework/playframework#7248

@cb372 I'd like to work this into https://github.com/playframework/play-scala-starter-example if possible (the license is different)

### CODE REVIEW

**Comment by cb372** [comment]
The new `FormAction` looks great 👍 

But I don't see the value in switching from compile-time to runtime DI. I'm biased (it's no secret that I dislike runtime DI), but as this repo is a tutorial I think it's helpful to show (to a reasonable level of detail) how everything is wired together.

**Comment by cb372** [comment]
I'm no expert on licences, but I have no problem with this code getting moved into a different project.

**Comment by beastyrabbit** [comment]
I tryed it. Got 2 Problems.
1:  2.6.0-SNAPSHOT is not valid. 2.6.0-M5 is so i canged it. 
2:  I got compiler Errors with FormAction and FormRequestHeader

**Comment by wsargent** [comment]
Yeah, this was changed to MessagesAction.  Will tweak again...

**Pull request closed without merging**
